global:
  resolve_timeout: 5m
  slack_api_url: https://hooks.slack.com/services/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
inhibit_rules:
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = critical
  target_matchers:
  - severity =~ warning|info
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = warning
  target_matchers:
  - severity = info
- equal:
  - namespace
  source_matchers:
  - alertname = InfoInhibitor
  target_matchers:
  - severity = info
receivers:
- name: "slack"
  slack_configs:
    - channel: "#general"
      send_resolved: "true"
      text: "summary: demosummary all"
route:
  group_by:
  - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: "slack"
  repeat_interval: 12h
  routes:
  - matchers:
    - alertname =~ "InfoInhibitor|Watchdog"
    receiver: "null"
templates:
- /etc/alertmanager/config/*.tmplroot