apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: javawebappvirtualsvc
spec:
  hosts:
    - "javaservicemeshgateway"
  http:
  - route:
    - destination:
        host: web-appsvc.default.svc.cluster.local
        subset: v1
      weight: 80
    - destination:
        host: web-appsvc-updated.default.svc.cluster.local
        subset: v2
      weight: 20