apiVersion: v1
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name            es
        Match           *
        Include_Tag_Key true
        Tag_Key         tags
        Port            443
        TLS             On
        TLS.Verify      Off
        Index           search-fluentbit
        Suppress_Type_Name On
        cloud_id        NewDeploy:dXMtZWFzdC0xLmF3cy5mb3VuZC5pbyQxZDNlNGVmMmE1NmU0MjZiYjZjZWY2Y2NhZDE2MDdhZSRjZGEzM2QyYjYyOGE0NzcxOWVjM2FlN2ExNDg3N2U5Yw==
        cloud_auth      elastic:js0G5WVJy8WsrXELMfKrvEWs

    [OUTPUT]
        Name es
        Include_Tag_Key true
        Tag_Key tags
        # Host newdeploy.kb.us-east-1.aws.elastic-cloud.com
        # Logstash_Format On
        Port            443
        tls             On
        tls.verify      Off
        Suppress_Type_Name On
        Index           search-fluentbit
        cloud_id        NewDeploy:dXMtZWFzdC0xLmF3cy5mb3VuZC5pbyQxZDNlNGVmMmE1NmU0MjZiYjZjZWY2Y2NhZDE2MDdhZSRjZGEzM2QyYjYyOGE0NzcxOWVjM2FlN2ExNDg3N2U5Yw==
        cloud_auth elastic:js0G5WVJy8WsrXELMfKrvEWs
        # Retry_Limit     False
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: fluent-bit
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-06-06T09:06:36Z"
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 2.1.4
    helm.sh/chart: fluent-bit-0.30.3
  name: fluent-bit
  namespace: default
  resourceVersion: "10357"
  uid: 7a206edd-9f38-4c4e-aa83-937f5344f562
