apiVersion: v1
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
    [PARSER]
        Name    demo
        Format  regex
        Regex   ^(?<namespace_name>[^_]+).(?<container_name>.+).(?<pod_name>a-z0-9?(?:.a-z0-9?)*).(?<docker_id>[a-z0-9]{64})-
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Kube_URL  https://kubernetes.default.svc:443
        Kube_CA_File  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log_Key log_processed
    [FILTER]
        Name grep
        match *
        Regex $kubernetes['namespace_name'] kube-system
    [OUTPUT]
        Name    stdout
        Match   kube.*
    [OUTPUT]
        Name            es
        Include_Tag_Key true
        Tag_Key         tags
        Match           kube.*
        Port            443
        TLS             On
        TLS.Verify      Off
        Index           search-k8s-system
        Suppress_Type_Name On
        cloud_id        NewDeploy:dXMtZWFzdC0xLmF3cy5mb3VuZC5pbyQxZDNlNGVmMmE1NmU0MjZiYjZjZWY2Y2NhZDE2MDdhZSRjZGEzM2QyYjYyOGE0NzcxOWVjM2FlN2ExNDg3N2U5Yw==
        cloud_auth      elastic:js0G5WVJy8WsrXELMfKrvEWs
        Trace_Error     On
        Trace_Output    On
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"custom_parsers.conf":"[PARSER]\n    Name docker_no_time\n    Format json\n    Time_Keep Off\n    Time_Key time\n    Time_Format %Y-%m-%dT%H:%M:%S.%L\n","fluent-bit.conf":"[SERVICE]\n    Daemon Off\n    Flush 1\n    Log_Level info\n    Parsers_File parsers.conf\n    Parsers_File custom_parsers.conf\n    HTTP_Server On\n    HTTP_Listen 0.0.0.0\n    HTTP_Port 2020\n    Health_Check On\n\n[INPUT]\n    Name tail\n    Path /var/log/containers/*.log\n    multiline.parser docker, cri\n    Tag kube.*\n    Mem_Buf_Limit 5MB\n    Skip_Long_Lines On\n\n[INPUT]\n    Name systemd\n    Tag host.*\n    Systemd_Filter _SYSTEMD_UNIT=kubelet.service\n    Read_From_Tail On\n\n[FILTER]\n    Name kubernetes\n    Match kube.*\n    Merge_Log On\n    Keep_Log Off\n    K8S-Logging.Parser On\n    K8S-Logging.Exclude On\n\n# [OUTPUT]\n#     Name            es\n#     Match           kube.*\n#     Host            newdeploy.kb.us-east-1.aws.elastic-cloud.com\n#     Logstash_Format On\n#     Port            9243\n#     TLS             On\n#     TLS.Verify      Off\n#     HTTP_User       elastic\n#     HTTP_Passwd     js0G5WVJy8WsrXELMfKrvEWs\n#     Index           fluentbit\n#     Retry_Limit     False\n\n[OUTPUT]\n    Name es\n    # Match host.*\n    Include_Tag_Key true\n    Tag_Key tags\n    # Host newdeploy.kb.us-east-1.aws.elastic-cloud.com\n    # Logstash_Format On\n    Port            443\n    tls             On\n    tls.verify      Off\n    Suppress_Type_Name On\n    Index           fluentbithost\n    cloud_id        NewDeploy:dXMtZWFzdC0xLmF3cy5mb3VuZC5pbyQxZDNlNGVmMmE1NmU0MjZiYjZjZWY2Y2NhZDE2MDdhZSRjZGEzM2QyYjYyOGE0NzcxOWVjM2FlN2ExNDg3N2U5Yw==\n    cloud_auth elastic:js0G5WVJy8WsrXELMfKrvEWs\n    # Retry_Limit     False\n"},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"fluent-bit","meta.helm.sh/release-namespace":"default"},"creationTimestamp":"2023-06-06T09:06:36Z","labels":{"app.kubernetes.io/instance":"fluent-bit","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"fluent-bit","app.kubernetes.io/version":"2.1.4","helm.sh/chart":"fluent-bit-0.30.3"},"name":"fluent-bit","namespace":"default","resourceVersion":"10357","uid":"7a206edd-9f38-4c4e-aa83-937f5344f562"}}
    meta.helm.sh/release-name: fluent-bit
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-06-06T09:06:36Z"
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 2.1.4
    helm.sh/chart: fluent-bit-0.30.3
  name: fluent-bit
  namespace: default
  resourceVersion: "29376"
  uid: 7a206edd-9f38-4c4e-aa83-937f5344f562
