apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: 
  name: web-appsvc-monitor
  labels:
    release: prometheus-operator
    app: prometheus

spec:
  jobLabel: job #taken from the web-appsvc labels
  endpoints:
    - interval: 30s
      port: web
      path: /actuator/prometheus
  selector:
    matchLabels:
      app: javawebapp 