apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwappv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebappv2
  template:
    metadata:
      labels:
        app: javawebappv2
        version: v2
    spec:
      containers:
        - name: javawebappcontainer
          image: xi4210asoni/java-web-server:0.1.3
          env:
            - name: POSTGRES_HOST
              value: postgresqlsvc
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: conn-secret
                  key: POSTGRES_PASSWORD
            - name: CONN
              valueFrom:
                secretKeyRef:
                  name: conn-secret
                  key: POSTGRES_CONN
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jwappsvcv2
  labels:
    job: java-api
    app: jwappsvcv2
spec:
  selector:
    app: javawebappv2
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
