apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-postgres
  namespace: {{.Values.namespace}}
spec:
  ingressClassName: nginx
  rules:
  - host: demo.localdeva.me
    http:
      paths:
      - pathType: Prefix
        path: /web-app
        backend:
          service:
            name: {{ .Release.Name }}-javawebappsvc
            port: 
              number: 8080