apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-postgres
  namespace: {{.Values.namespace}}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Release.Name }}-webappsvc
            port: 
              number: 8080