apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-javawebappdeploy
  namespace: {{.Values.namespace}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
        - name: javawebappcontainer
          image: {{.Values.imagename}}:{{.Values.imagetag}}
          imagePullPolicy: {{.Values.pullpolicy}}
          env:
            - name: POSTGRES_HOST
              value: postgresql
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-connsecret
                  key: POSTGRES_PASSWORD
            - name: CONN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-connsecret
                  key: POSTGRES_CONN
          ports:
            - containerPort: 8080
      volumes:
        - name: config-volume
          configMap:
            name: java-webapp-configs
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-javawebappsvc
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: javawebapp
  ports:
    - port: 8080 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres
          imagePullPolicy: {{.Values.pullpolicy}}
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-connsecret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
  type: ClusterIP


