apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-connsecret
  namespace: {{.Values.namespace}}
type: Opaque
data:
  POSTGRES_PASSWORD: dGVzdC1kYi1wYXNzd29yZA==
  POSTGRES_CONN: amRiYzpwb3N0Z3Jlc3FsOi8vZGVtbzItcG9zdGdyZXNxbDo1NDMyL3Bvc3RncmVzP3VzZXI9cG9zdGdyZXMmcGFzc3dvcmQ9dGVzdC1kYi1wYXNzd29yZA==