apiVersion: constraints.gatekeeper.sh/v1beta1
kind:  DisallowPEdeployments
metadata:
  name: disallow-pe-deploy-constraint
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]